[build]
builder = "nixpacks"
buildCommand = "go build -o main cmd/server/main.go && go build -o migrate cmd/migrate/main.go"

[deploy]
startCommand = "./main"
healthcheckPath = "/healthz"
restartPolicyType = "on_failure"

[[deploy.environmentVariables]]
name = "PORT"
value = "8080"